### ISSUE TITLE
detail view design issues

### ISSUE THREAD

**Issue by saipraneshm** [Codepath-Group7/Group7#51]
![screenshot_1508955396](https://user-images.githubusercontent.com/18727680/32015530-36ef9ad0-b976-11e7-9fc0-d2a93646592e.png)

**Comment by saipraneshm** [comment]
Update reviews recycler view as well, assign constant width and height to the images and maybe later the text size of title and review text

![screenshot_1508955712](https://user-images.githubusercontent.com/18727680/32015709-ba87d8bc-b976-11e7-8a46-24d7c9875ece.png)

**Comment by akshaymathur90** [comment]
which device are you testing on, please let me know the screen density and size if possible
